### ISSUE TITLE
Remove Phone Number Detection

### ISSUE THREAD

**Issue by dawsonloudon** [duhduhdan/Explore-SWAPI#3]
Numbers that could be phone # are being highlighted

Resolve:
add tagging to remove this

**Comment by duhduhdan** [comment]
Added  ``<meta name="format-detection" content="telephone=no">``

**Comment by dawsonloudon** [comment]
Can you commit and push that? I am not seeing it

**Comment by dawsonloudon** [comment]
I added this and pushed it, its all good now
